/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alejandro Serrano Loredo
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    ConectorBBDD conector = new ConectorBBDD();

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        //Se inicie en el centro de la pantalla
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSeleccion = new javax.swing.ButtonGroup();
        jLabelMensaje = new javax.swing.JLabel();
        jButtonConexion = new javax.swing.JButton();
        jButtonDesconexion = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelAlbumes = new javax.swing.JPanel();
        jButtonDisplayAlbum = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Display_Album = new javax.swing.JTable();
        jLabelTituloAlbum = new javax.swing.JLabel();
        jTextFieldTituloAlbum = new javax.swing.JTextField();
        jLabelTituloGrupo = new javax.swing.JLabel();
        jTextFieldGrupo = new javax.swing.JTextField();
        jLabelTituloDuracionAlbum = new javax.swing.JLabel();
        jTextFieldDuracionAlbum = new javax.swing.JTextField();
        jLabelTituloProductor = new javax.swing.JLabel();
        jTextFieldProductor = new javax.swing.JTextField();
        jButtonAnnadirAlbum = new javax.swing.JButton();
        jButtonModificarAlbum = new javax.swing.JButton();
        jButtonBorrarAlbum = new javax.swing.JButton();
        jPanelCanciones = new javax.swing.JPanel();
        jButtonDisplayCanciones = new javax.swing.JButton();
        jLabelSeleccion = new javax.swing.JLabel();
        jRadioButtonAlbum = new javax.swing.JRadioButton();
        jComboBoxSeleccionAlbum = new javax.swing.JComboBox<>();
        jRadioButtonDuracion = new javax.swing.JRadioButton();
        jTextFieldSeleccionDuracion = new javax.swing.JTextField();
        jComboBoxDuracionOrden = new javax.swing.JComboBox<>();
        jButtonDisplayCancionSeleccionada = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Display_Cancion = new javax.swing.JTable();
        jLabelTituloCancion = new javax.swing.JLabel();
        jTextFieldTituloCancion = new javax.swing.JTextField();
        jLabelDuracionCancion = new javax.swing.JLabel();
        jTextFieldDuracionCancion = new javax.swing.JTextField();
        jLabelEscritor = new javax.swing.JLabel();
        jTextFieldEscritor = new javax.swing.JTextField();
        jLabelAlbum = new javax.swing.JLabel();
        jComboBoxAlbum = new javax.swing.JComboBox<>();
        jButtonAnnadirCancion = new javax.swing.JButton();
        jButtonModificarCancion = new javax.swing.JButton();
        jButtonBorrarCancion = new javax.swing.JButton();
        jPanelAdmin = new javax.swing.JPanel();
        jTextFieldAnnadirCampo = new javax.swing.JTextField();
        jComboBoxCampo = new javax.swing.JComboBox<>();
        jComboBoxTabla = new javax.swing.JComboBox<>();
        jTextFieldVarSize = new javax.swing.JTextField();
        jButtonAnnadirCampo = new javax.swing.JButton();
        jLabelAgregarCampos = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jLabelDimension = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jButtonConexion.setText("Conectar a la BBDD");
        jButtonConexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConexionActionPerformed(evt);
            }
        });

        jButtonDesconexion.setText("Desconectar de la BBDD");
        jButtonDesconexion.setEnabled(false);
        jButtonDesconexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDesconexionActionPerformed(evt);
            }
        });

        jButtonDisplayAlbum.setText("Mostrar Todo");
        jButtonDisplayAlbum.setEnabled(false);
        jButtonDisplayAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDisplayAlbumActionPerformed(evt);
            }
        });

        jTable_Display_Album.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "titulo", "grupo", "duracion", "productor"
            }
        ));
        jTable_Display_Album.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Display_AlbumMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Display_Album);

        jLabelTituloAlbum.setText("Título *");

        jLabelTituloGrupo.setText("Grupo *");

        jLabelTituloDuracionAlbum.setText("Duración");

        jLabelTituloProductor.setText("Productor");

        jButtonAnnadirAlbum.setText("Añadir");
        jButtonAnnadirAlbum.setEnabled(false);
        jButtonAnnadirAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnadirAlbumActionPerformed(evt);
            }
        });

        jButtonModificarAlbum.setText("Modificar");
        jButtonModificarAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarAlbumActionPerformed(evt);
            }
        });

        jButtonBorrarAlbum.setText("Borrar");
        jButtonBorrarAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarAlbumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAlbumesLayout = new javax.swing.GroupLayout(jPanelAlbumes);
        jPanelAlbumes.setLayout(jPanelAlbumesLayout);
        jPanelAlbumesLayout.setHorizontalGroup(
            jPanelAlbumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlbumesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAlbumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
                    .addGroup(jPanelAlbumesLayout.createSequentialGroup()
                        .addComponent(jButtonDisplayAlbum)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelAlbumesLayout.createSequentialGroup()
                        .addGroup(jPanelAlbumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAlbumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelTituloAlbum, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldTituloAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonAnnadirAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelAlbumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelTituloGrupo)
                            .addComponent(jTextFieldGrupo)
                            .addComponent(jButtonModificarAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAlbumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDuracionAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTituloDuracionAlbum))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAlbumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelTituloProductor)
                            .addComponent(jTextFieldProductor)
                            .addComponent(jButtonBorrarAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanelAlbumesLayout.setVerticalGroup(
            jPanelAlbumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlbumesLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButtonDisplayAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAlbumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTituloAlbum)
                    .addComponent(jLabelTituloGrupo)
                    .addComponent(jLabelTituloDuracionAlbum)
                    .addComponent(jLabelTituloProductor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAlbumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTituloAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDuracionAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldProductor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAlbumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonBorrarAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonModificarAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAnnadirAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Álbumes", jPanelAlbumes);

        jButtonDisplayCanciones.setText("Mostrar Todo");
        jButtonDisplayCanciones.setEnabled(false);
        jButtonDisplayCanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDisplayCancionesActionPerformed(evt);
            }
        });

        jLabelSeleccion.setText("Buscar cancion:");

        buttonGroupSeleccion.add(jRadioButtonAlbum);
        jRadioButtonAlbum.setText("Album");

        jComboBoxSeleccionAlbum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonGroupSeleccion.add(jRadioButtonDuracion);
        jRadioButtonDuracion.setText("Duración");

        jComboBoxDuracionOrden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonDisplayCancionSeleccionada.setText("Mostrar");
        jButtonDisplayCancionSeleccionada.setEnabled(false);
        jButtonDisplayCancionSeleccionada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDisplayCancionSeleccionadaActionPerformed(evt);
            }
        });

        jTable_Display_Cancion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "titulo", "duracion", "escritor", "album"
            }
        ));
        jTable_Display_Cancion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Display_CancionMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_Display_Cancion);

        jLabelTituloCancion.setText("Título *");

        jLabelDuracionCancion.setText("Duración");

        jLabelEscritor.setText("Escritor");

        jLabelAlbum.setText("Album");

        jComboBoxAlbum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonAnnadirCancion.setText("Añadir");
        jButtonAnnadirCancion.setEnabled(false);
        jButtonAnnadirCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnadirCancionActionPerformed(evt);
            }
        });

        jButtonModificarCancion.setText("Modificar");
        jButtonModificarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarCancionActionPerformed(evt);
            }
        });

        jButtonBorrarCancion.setText("Borrar");
        jButtonBorrarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarCancionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCancionesLayout = new javax.swing.GroupLayout(jPanelCanciones);
        jPanelCanciones.setLayout(jPanelCancionesLayout);
        jPanelCancionesLayout.setHorizontalGroup(
            jPanelCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCancionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanelCancionesLayout.createSequentialGroup()
                        .addComponent(jButtonDisplayCanciones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                        .addGroup(jPanelCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCancionesLayout.createSequentialGroup()
                                .addGroup(jPanelCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonDuracion)
                                    .addComponent(jRadioButtonAlbum))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelCancionesLayout.createSequentialGroup()
                                        .addComponent(jComboBoxDuracionOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldSeleccionDuracion))
                                    .addComponent(jComboBoxSeleccionAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButtonDisplayCancionSeleccionada))
                            .addComponent(jLabelSeleccion)))
                    .addGroup(jPanelCancionesLayout.createSequentialGroup()
                        .addGroup(jPanelCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelTituloCancion)
                            .addComponent(jButtonAnnadirCancion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jTextFieldTituloCancion))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonModificarCancion, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jLabelDuracionCancion)
                            .addComponent(jTextFieldDuracionCancion))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEscritor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEscritor))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxAlbum, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelCancionesLayout.createSequentialGroup()
                                .addComponent(jLabelAlbum)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jButtonBorrarCancion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanelCancionesLayout.setVerticalGroup(
            jPanelCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCancionesLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabelSeleccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCancionesLayout.createSequentialGroup()
                        .addGroup(jPanelCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonAlbum)
                            .addComponent(jComboBoxSeleccionAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxDuracionOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButtonDuracion)
                                .addComponent(jTextFieldSeleccionDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButtonDisplayCancionSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDisplayCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTituloCancion)
                    .addComponent(jLabelDuracionCancion)
                    .addComponent(jLabelEscritor)
                    .addComponent(jLabelAlbum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldTituloCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldDuracionCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldEscritor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanelCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonBorrarCancion, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jButtonAnnadirCancion, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jButtonModificarCancion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Canciones", jPanelCanciones);

        jComboBoxCampo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxTabla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonAnnadirCampo.setText("Añadir");
        jButtonAnnadirCampo.setEnabled(false);
        jButtonAnnadirCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnadirCampoActionPerformed(evt);
            }
        });

        jLabelAgregarCampos.setText("Agregar nuevos campos");

        jLabelTipo.setText("Tipo");

        jLabelDimension.setText("Dimensión");

        javax.swing.GroupLayout jPanelAdminLayout = new javax.swing.GroupLayout(jPanelAdmin);
        jPanelAdmin.setLayout(jPanelAdminLayout);
        jPanelAdminLayout.setHorizontalGroup(
            jPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAdminLayout.createSequentialGroup()
                        .addComponent(jTextFieldAnnadirCampo, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAdminLayout.createSequentialGroup()
                        .addComponent(jLabelAgregarCampos)
                        .addGap(291, 291, 291)
                        .addComponent(jLabelTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxTabla, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDimension, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jTextFieldVarSize, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAnnadirCampo)
                .addContainerGap())
        );
        jPanelAdminLayout.setVerticalGroup(
            jPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAgregarCampos)
                    .addComponent(jLabelDimension)
                    .addComponent(jLabelTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAnnadirCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAnnadirCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldVarSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(511, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Admin", jPanelAdmin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDesconexion)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDesconexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonConexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConexionActionPerformed

        if (conector.ConectarBBDD() == -1) {
            this.jLabelMensaje.setText("ERROR en la conexión a la BBDD discografica.");
            this.jButtonConexion.setEnabled(false);
            this.jButtonDesconexion.setEnabled(false);
            this.jButtonAnnadirCampo.setEnabled(false);
            this.jButtonDisplayAlbum.setEnabled(false);
            this.jButtonAnnadirAlbum.setEnabled(false);
            this.jButtonAnnadirCancion.setEnabled(false);
            this.jButtonDisplayAlbum.setEnabled(false);
            this.jButtonDisplayCanciones.setEnabled(false);
            this.jButtonDisplayCancionSeleccionada.setEnabled(false);
        } else {
            this.jLabelMensaje.setText("Conectado a discografica.");
            this.jButtonConexion.setEnabled(false);
            this.jButtonDesconexion.setEnabled(true);
            this.jButtonAnnadirCampo.setEnabled(true);
            this.jButtonDisplayAlbum.setEnabled(true);
            this.jButtonAnnadirAlbum.setEnabled(true);
            this.jButtonAnnadirCancion.setEnabled(true);
            this.jButtonDisplayAlbum.setEnabled(true);
            this.jButtonDisplayCanciones.setEnabled(true);
            this.jButtonDisplayCancionSeleccionada.setEnabled(true);
        }

        this.jComboBoxCampo.removeAllItems();
        String[] tipoDato = {"INTEGER", "TINYINT", "VARCHAR", "TIME", "YEAR", "BLOB"};

        for (String elemento : tipoDato) {
            this.jComboBoxCampo.addItem(elemento);
        }

        this.jComboBoxTabla.removeAllItems();
        String[] tablas = {"album", "cancion"};

        for (String elemento : tablas) {
            this.jComboBoxTabla.addItem(elemento);
        }

        this.jComboBoxAlbum.removeAllItems();
        this.jComboBoxSeleccionAlbum.removeAllItems();
        ArrayList<String> titulosAlbum = conector.getTitulosAlbum();
        if (titulosAlbum != null) {
            titulosAlbum.forEach((elemento) -> this.jComboBoxAlbum.addItem(elemento));
            titulosAlbum.forEach((elemento) -> this.jComboBoxSeleccionAlbum.addItem(elemento));
        }

        this.jComboBoxDuracionOrden.removeAllItems();
        String[] ordenDuracion = {"Ascendente","Descendente"};
        for (String elemento : ordenDuracion) {
            this.jComboBoxDuracionOrden.addItem(elemento);
        }

    }//GEN-LAST:event_jButtonConexionActionPerformed

    private void jButtonDesconexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDesconexionActionPerformed

        if (conector.cerrarConexion() == -1) {
            this.jLabelMensaje.setText("Error al cerrar la conexión.");
            this.jButtonConexion.setEnabled(false);
            this.jButtonDesconexion.setEnabled(false);
            this.jButtonAnnadirCampo.setEnabled(false);
            this.jButtonDisplayAlbum.setEnabled(false);
            this.jButtonAnnadirAlbum.setEnabled(false);
            this.jButtonAnnadirCancion.setEnabled(false);
        } else {
            this.jLabelMensaje.setText("Conexión cerrada correctamente.");
            this.jButtonConexion.setEnabled(true);
            this.jButtonDesconexion.setEnabled(false);
            this.jButtonAnnadirCampo.setEnabled(false);
            this.jButtonDisplayAlbum.setEnabled(false);
            this.jButtonAnnadirAlbum.setEnabled(false);
            this.jButtonAnnadirCancion.setEnabled(false);
        }

    }//GEN-LAST:event_jButtonDesconexionActionPerformed

    private void jButtonAnnadirCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnadirCampoActionPerformed

        int resultadoModificacion = conector.annadirCampo(this.jComboBoxTabla.getSelectedItem().toString(), this.jTextFieldAnnadirCampo.getText(), this.jComboBoxCampo.getSelectedItem().toString(), this.jTextFieldVarSize.getText());

        switch (resultadoModificacion) {
            case -1:
                this.jLabelMensaje.setText("La columna existe en la base de datos.");
                this.jButtonConexion.setEnabled(false);
                this.jButtonDesconexion.setEnabled(true);
                this.jButtonAnnadirCampo.setEnabled(false);
                this.jButtonDisplayAlbum.setEnabled(true);
                break;
            case -2:
                this.jLabelMensaje.setText("Error al añadir publicación.");
                this.jButtonConexion.setEnabled(false);
                this.jButtonDesconexion.setEnabled(true);
                this.jButtonAnnadirCampo.setEnabled(false);
                this.jButtonDisplayAlbum.setEnabled(true);
                break;
            default:
                this.jLabelMensaje.setText("Columna añadida satisfactoriamente.");
                this.jButtonConexion.setEnabled(false);
                this.jButtonDesconexion.setEnabled(true);
                this.jButtonAnnadirCampo.setEnabled(false);
                this.jButtonDisplayAlbum.setEnabled(true);
                break;
        }

    }//GEN-LAST:event_jButtonAnnadirCampoActionPerformed

    private void jButtonDisplayAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDisplayAlbumActionPerformed

        show_album();        

    }//GEN-LAST:event_jButtonDisplayAlbumActionPerformed

    private void jButtonDisplayCancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDisplayCancionesActionPerformed
        
        show_cancion();
        
    }//GEN-LAST:event_jButtonDisplayCancionesActionPerformed

    private void jButtonAnnadirCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnadirCancionActionPerformed
        
        if(conector.annadirCancion(jTextFieldTituloCancion.getText(), jTextFieldDuracionCancion.getText(), jTextFieldEscritor.getText(), Integer.parseInt(jComboBoxAlbum.getSelectedItem().toString().substring(0, 1))) == -1){
            this.jLabelMensaje.setText("Error al añadir canción.");
        } else {
            this.jLabelMensaje.setText("Canción añadida satisfactoriamente.");
        }
        
    }//GEN-LAST:event_jButtonAnnadirCancionActionPerformed

    private void jButtonDisplayCancionSeleccionadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDisplayCancionSeleccionadaActionPerformed
                
        if(this.jRadioButtonAlbum.isSelected()){
            show_cancionFiltroAlbum(Integer.parseInt(jComboBoxSeleccionAlbum.getSelectedItem().toString().substring(0, 1)));
        } else if (this.jRadioButtonDuracion.isSelected()) {
            show_cancionFiltroDuracion(this.jTextFieldSeleccionDuracion.getText() ,this.jComboBoxDuracionOrden.getSelectedIndex());
        }
        
    }//GEN-LAST:event_jButtonDisplayCancionSeleccionadaActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
        try {
            if(!conector.conexion.isClosed()){
                conector.cerrarConexion();
            }
        } catch (SQLException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_formWindowClosed

    private void jTable_Display_CancionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Display_CancionMouseClicked

        //Set data to their textField
        DefaultTableModel tblModel = (DefaultTableModel) jTable_Display_Cancion.getModel();

        //Set data to text fiel when raw is selected
        String titulo = tblModel.getValueAt(jTable_Display_Cancion.getSelectedRow(), 1).toString();
        String duracion = tblModel.getValueAt(jTable_Display_Cancion.getSelectedRow(), 2).toString();
        String escritor = tblModel.getValueAt(jTable_Display_Cancion.getSelectedRow(), 3).toString();
        String album = String.valueOf(titulo.charAt(0));

        //set to textfield
        this.jTextFieldTituloCancion.setText(titulo);
        this.jTextFieldDuracionCancion.setText(duracion);
        this.jTextFieldEscritor.setText(escritor);
        this.jComboBoxAlbum.setSelectedIndex(Integer.parseInt(album)-1);
        
        

    }//GEN-LAST:event_jTable_Display_CancionMouseClicked

    private void jButtonModificarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarCancionActionPerformed
        
        if(jTable_Display_Cancion.getSelectedRowCount() == 1){
            //Set data to their textField
            DefaultTableModel tblModel = (DefaultTableModel) jTable_Display_Cancion.getModel();
            //if single row is selected than update
            String id = tblModel.getValueAt(jTable_Display_Cancion.getSelectedRow(), 0).toString();
            String titulo = this.jTextFieldTituloCancion.getText();
            String duracion = this.jTextFieldDuracionCancion.getText();
            String escritor = this.jTextFieldEscritor.getText();
            int album = Integer.parseInt(String.valueOf(titulo.charAt(0)));

            conector.updateCancion(id, titulo, duracion, escritor, album);
        }
        
    }//GEN-LAST:event_jButtonModificarCancionActionPerformed

    private void jButtonBorrarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarCancionActionPerformed
        
        if(jTable_Display_Cancion.getSelectedRowCount() == 1){
            //Set data to their textField
            DefaultTableModel tblModel = (DefaultTableModel) jTable_Display_Cancion.getModel();
            //if single row is selected than update
            int id = Integer.parseInt(tblModel.getValueAt(jTable_Display_Cancion.getSelectedRow(), 0).toString());

            conector.deleteCancion(id);
        }
        
    }//GEN-LAST:event_jButtonBorrarCancionActionPerformed

    private void jButtonModificarAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarAlbumActionPerformed
        
        if(jTable_Display_Album.getSelectedRowCount() == 1){
            //Set data to their textField
            DefaultTableModel tblModel = (DefaultTableModel) jTable_Display_Album.getModel();
            //if single row is selected than update
            String id = tblModel.getValueAt(jTable_Display_Album.getSelectedRow(), 0).toString();
            String titulo = this.jTextFieldTituloAlbum.getText();
            String grupo = this.jTextFieldGrupo.getText();
            String duracion = this.jTextFieldDuracionCancion.getText();
            String escritor = this.jTextFieldEscritor.getText();
            
            conector.updateAlbum(id, titulo, grupo, duracion, escritor);
        }
        
    }//GEN-LAST:event_jButtonModificarAlbumActionPerformed

    private void jButtonBorrarAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarAlbumActionPerformed
        
        if(jTable_Display_Album.getSelectedRowCount() == 1){
            //Set data to their textField
            DefaultTableModel tblModel = (DefaultTableModel) jTable_Display_Album.getModel();
            //if single row is selected than update
            int id = Integer.parseInt(tblModel.getValueAt(jTable_Display_Album.getSelectedRow(), 0).toString());

            conector.deleteAlbum(id);
        }
        
    }//GEN-LAST:event_jButtonBorrarAlbumActionPerformed

    private void jButtonAnnadirAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnadirAlbumActionPerformed

        if (conector.annadirAlbum(jTextFieldTituloAlbum.getText(), jTextFieldGrupo.getText(), jTextFieldDuracionAlbum.getText(), jTextFieldProductor.getText()) == -1) {
            this.jLabelMensaje.setText("Error al añadir album.");
        } else {
            this.jLabelMensaje.setText("Album añadido satisfactoriamente.");
        }
    }//GEN-LAST:event_jButtonAnnadirAlbumActionPerformed

    private void jTable_Display_AlbumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Display_AlbumMouseClicked
        
        //Set data to their textField
        DefaultTableModel tblModel = (DefaultTableModel) jTable_Display_Album.getModel();

        //Set data to text fiel when raw is selected
        String titulo = tblModel.getValueAt(jTable_Display_Album.getSelectedRow(), 1).toString();
        String grupo = tblModel.getValueAt(jTable_Display_Album.getSelectedRow(), 2).toString();
        String duracion = tblModel.getValueAt(jTable_Display_Album.getSelectedRow(), 3).toString();
        String productor = tblModel.getValueAt(jTable_Display_Album.getSelectedRow(), 4).toString();

        //set to textfield
        this.jTextFieldTituloAlbum.setText(titulo);
        this.jTextFieldGrupo.setText(grupo);
        this.jTextFieldDuracionAlbum.setText(duracion);
        this.jTextFieldProductor.setText(productor);
        
    }//GEN-LAST:event_jTable_Display_AlbumMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupSeleccion;
    private javax.swing.JButton jButtonAnnadirAlbum;
    private javax.swing.JButton jButtonAnnadirCampo;
    private javax.swing.JButton jButtonAnnadirCancion;
    private javax.swing.JButton jButtonBorrarAlbum;
    private javax.swing.JButton jButtonBorrarCancion;
    private javax.swing.JButton jButtonConexion;
    private javax.swing.JButton jButtonDesconexion;
    private javax.swing.JButton jButtonDisplayAlbum;
    private javax.swing.JButton jButtonDisplayCancionSeleccionada;
    private javax.swing.JButton jButtonDisplayCanciones;
    private javax.swing.JButton jButtonModificarAlbum;
    private javax.swing.JButton jButtonModificarCancion;
    private javax.swing.JComboBox<String> jComboBoxAlbum;
    private javax.swing.JComboBox<String> jComboBoxCampo;
    private javax.swing.JComboBox<String> jComboBoxDuracionOrden;
    private javax.swing.JComboBox<String> jComboBoxSeleccionAlbum;
    private javax.swing.JComboBox<String> jComboBoxTabla;
    private javax.swing.JLabel jLabelAgregarCampos;
    private javax.swing.JLabel jLabelAlbum;
    private javax.swing.JLabel jLabelDimension;
    private javax.swing.JLabel jLabelDuracionCancion;
    private javax.swing.JLabel jLabelEscritor;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JLabel jLabelSeleccion;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelTituloAlbum;
    private javax.swing.JLabel jLabelTituloCancion;
    private javax.swing.JLabel jLabelTituloDuracionAlbum;
    private javax.swing.JLabel jLabelTituloGrupo;
    private javax.swing.JLabel jLabelTituloProductor;
    private javax.swing.JPanel jPanelAdmin;
    private javax.swing.JPanel jPanelAlbumes;
    private javax.swing.JPanel jPanelCanciones;
    private javax.swing.JRadioButton jRadioButtonAlbum;
    private javax.swing.JRadioButton jRadioButtonDuracion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_Display_Album;
    private javax.swing.JTable jTable_Display_Cancion;
    private javax.swing.JTextField jTextFieldAnnadirCampo;
    private javax.swing.JTextField jTextFieldDuracionAlbum;
    private javax.swing.JTextField jTextFieldDuracionCancion;
    private javax.swing.JTextField jTextFieldEscritor;
    private javax.swing.JTextField jTextFieldGrupo;
    private javax.swing.JTextField jTextFieldProductor;
    private javax.swing.JTextField jTextFieldSeleccionDuracion;
    private javax.swing.JTextField jTextFieldTituloAlbum;
    private javax.swing.JTextField jTextFieldTituloCancion;
    private javax.swing.JTextField jTextFieldVarSize;
    // End of variables declaration//GEN-END:variables

    public void show_album() {

        ArrayList<Album> list = conector.albumList();
        DefaultTableModel model = (DefaultTableModel) jTable_Display_Album.getModel();
        model.setRowCount(0);
        Object[] row = new Object[5];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getTitulo();
            row[2] = list.get(i).getGrupo();
            row[3] = list.get(i).getDuracion();
            row[4] = list.get(i).getProductor();
            model.addRow(row);
        }
    }
    
    
    public void show_cancion() {

        ArrayList<Cancion> list = conector.cancionList();
        DefaultTableModel model = (DefaultTableModel) jTable_Display_Cancion.getModel();
        model.setRowCount(0);
        Object[] row = new Object[5];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getTitulo();
            row[2] = list.get(i).getDuracion();
            row[3] = list.get(i).getEscritor();
            row[4] = list.get(i).getAlbum();
            model.addRow(row);
        }
    }
    
    public void show_cancionFiltroAlbum(int _album) {
        
        ArrayList<Cancion> list = conector.cancionListFiltroAlbum(_album);
        DefaultTableModel model = (DefaultTableModel) jTable_Display_Cancion.getModel();
        model.setRowCount(0);
        Object[] row = new Object[5];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getTitulo();
            row[2] = list.get(i).getDuracion();
            row[3] = list.get(i).getEscritor();
            row[4] = list.get(i).getAlbum();
            model.addRow(row);
        }
    }
    
    public void show_cancionFiltroDuracion(String _duracion, int _orden) {

        ArrayList<Cancion> list = conector.cancionListFiltroDuracion(_duracion, _orden);
        DefaultTableModel model = (DefaultTableModel) jTable_Display_Cancion.getModel();
        model.setRowCount(0);
        Object[] row = new Object[5];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getTitulo();
            row[2] = list.get(i).getDuracion();
            row[3] = list.get(i).getEscritor();
            row[4] = list.get(i).getAlbum();
            model.addRow(row);
        }
    }
    
}
