/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.ArrayList;

/**
 *
 * @author Alejandro Serrano Loredo
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    ConectorBBDD conector = new ConectorBBDD();

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        //Se inicie en el centro de la pantalla
        this.setLocationRelativeTo(null);
        //No se puede redimensionar
        //this.setUndecorated(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMensaje = new javax.swing.JLabel();
        jButtonConexion = new javax.swing.JButton();
        jButtonDesconexion = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelUser = new javax.swing.JPanel();
        jButtonMostrarAlbumes = new javax.swing.JButton();
        jComboBoxUserDB = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaSalida = new javax.swing.JTextArea();
        jLabelTituloAlbum = new javax.swing.JLabel();
        jTextFieldTituloAlbum = new javax.swing.JTextField();
        jLabelTituloGrupo = new javax.swing.JLabel();
        jTextFieldGrupo = new javax.swing.JTextField();
        jLabelTituloDuracionAlbum = new javax.swing.JLabel();
        jTextFieldDuracionAlbum = new javax.swing.JTextField();
        jLabelTituloProductor = new javax.swing.JLabel();
        jTextFieldProductor = new javax.swing.JTextField();
        jButtonAnnadirAlbum = new javax.swing.JButton();
        jLabelTituloCancion = new javax.swing.JLabel();
        jTextFieldTituloCancion = new javax.swing.JTextField();
        jLabelDuracionCancion = new javax.swing.JLabel();
        jTextFieldDuracionCancion = new javax.swing.JTextField();
        jLabelEscritor = new javax.swing.JLabel();
        jTextFieldEscritor = new javax.swing.JTextField();
        jLabelAlbum = new javax.swing.JLabel();
        jButtonAnnadirCancion = new javax.swing.JButton();
        jComboBoxAlbum = new javax.swing.JComboBox<>();
        jPanelAdmin = new javax.swing.JPanel();
        jTextFieldAnnadirCampo = new javax.swing.JTextField();
        jComboBoxCampo = new javax.swing.JComboBox<>();
        jButtonAnnadirCampo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonConexion.setText("Conectar a la BBDD");
        jButtonConexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConexionActionPerformed(evt);
            }
        });

        jButtonDesconexion.setText("Desconectar de la BBDD");
        jButtonDesconexion.setEnabled(false);
        jButtonDesconexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDesconexionActionPerformed(evt);
            }
        });

        jButtonMostrarAlbumes.setText("Mostrar álbumes");
        jButtonMostrarAlbumes.setEnabled(false);
        jButtonMostrarAlbumes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarAlbumesActionPerformed(evt);
            }
        });

        jComboBoxUserDB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextAreaSalida.setColumns(20);
        jTextAreaSalida.setRows(5);
        jScrollPane2.setViewportView(jTextAreaSalida);

        jLabelTituloAlbum.setText("Título *");

        jLabelTituloGrupo.setText("Grupo *");

        jLabelTituloDuracionAlbum.setText("Duración");

        jLabelTituloProductor.setText("Productor");

        jButtonAnnadirAlbum.setText("Añadir album");
        jButtonAnnadirAlbum.setEnabled(false);
        jButtonAnnadirAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnadirAlbumActionPerformed(evt);
            }
        });

        jLabelTituloCancion.setText("Título *");

        jLabelDuracionCancion.setText("Duración");

        jLabelEscritor.setText("Escritor");

        jLabelAlbum.setText("Album");

        jButtonAnnadirCancion.setText("Añadir cancion");
        jButtonAnnadirCancion.setEnabled(false);
        jButtonAnnadirCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnadirCancionActionPerformed(evt);
            }
        });

        jComboBoxAlbum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanelUserLayout = new javax.swing.GroupLayout(jPanelUser);
        jPanelUser.setLayout(jPanelUserLayout);
        jPanelUserLayout.setHorizontalGroup(
            jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUserLayout.createSequentialGroup()
                .addGroup(jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanelUserLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelUserLayout.createSequentialGroup()
                                .addComponent(jButtonMostrarAlbumes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxUserDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelUserLayout.createSequentialGroup()
                                .addGroup(jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTituloAlbum)
                                    .addComponent(jTextFieldTituloAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTituloGrupo)
                                    .addComponent(jTextFieldGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTituloDuracionAlbum)
                                    .addComponent(jTextFieldDuracionAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelUserLayout.createSequentialGroup()
                                        .addComponent(jLabelTituloProductor)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanelUserLayout.createSequentialGroup()
                                        .addComponent(jTextFieldProductor, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonAnnadirAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanelUserLayout.createSequentialGroup()
                                .addGroup(jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTituloCancion)
                                    .addComponent(jTextFieldTituloCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDuracionCancion)
                                    .addComponent(jTextFieldDuracionCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelEscritor)
                                    .addComponent(jTextFieldEscritor, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelUserLayout.createSequentialGroup()
                                        .addComponent(jLabelAlbum)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanelUserLayout.createSequentialGroup()
                                        .addComponent(jComboBoxAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonAnnadirCancion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        jPanelUserLayout.setVerticalGroup(
            jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelUserLayout.createSequentialGroup()
                        .addComponent(jLabelTituloGrupo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelUserLayout.createSequentialGroup()
                        .addGroup(jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonMostrarAlbumes)
                            .addComponent(jComboBoxUserDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTituloAlbum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTituloAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelUserLayout.createSequentialGroup()
                        .addComponent(jLabelTituloDuracionAlbum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDuracionAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelUserLayout.createSequentialGroup()
                        .addComponent(jLabelTituloProductor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldProductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAnnadirAlbum))))
                .addGap(18, 18, 18)
                .addGroup(jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelUserLayout.createSequentialGroup()
                        .addComponent(jLabelDuracionCancion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDuracionCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelUserLayout.createSequentialGroup()
                        .addComponent(jLabelTituloCancion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTituloCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelUserLayout.createSequentialGroup()
                        .addComponent(jLabelEscritor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEscritor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelUserLayout.createSequentialGroup()
                        .addComponent(jLabelAlbum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAnnadirCancion)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Usuario", jPanelUser);

        jComboBoxCampo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonAnnadirCampo.setText("Agregar nuevos campos");
        jButtonAnnadirCampo.setEnabled(false);
        jButtonAnnadirCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnadirCampoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAdminLayout = new javax.swing.GroupLayout(jPanelAdmin);
        jPanelAdmin.setLayout(jPanelAdminLayout);
        jPanelAdminLayout.setHorizontalGroup(
            jPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldAnnadirCampo, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAnnadirCampo)
                .addGap(275, 275, 275))
        );
        jPanelAdminLayout.setVerticalGroup(
            jPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAnnadirCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAnnadirCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(471, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Administrador", jPanelAdmin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDesconexion)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonConexion)
                        .addComponent(jButtonDesconexion)))
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConexionActionPerformed
        
        if (conector.ConectarBBDD() == -1) {
            this.jLabelMensaje.setText("ERROR en la conexión a la BBDD discografica.");
            this.jButtonConexion.setEnabled(false);
            this.jButtonDesconexion.setEnabled(false);
            this.jButtonAnnadirCampo.setEnabled(false);
            this.jButtonMostrarAlbumes.setEnabled(false);
            this.jButtonAnnadirAlbum.setEnabled(false);
            this.jButtonAnnadirCancion.setEnabled(false);
        } else {
            this.jLabelMensaje.setText("Conectado a discografica.");
            this.jButtonConexion.setEnabled(false);
            this.jButtonDesconexion.setEnabled(true);
            this.jButtonAnnadirCampo.setEnabled(true);
            this.jButtonMostrarAlbumes.setEnabled(true);
            this.jButtonAnnadirAlbum.setEnabled(true);
            this.jButtonAnnadirCancion.setEnabled(true);
        }
        
        this.jComboBoxCampo.removeAllItems();
        String[] tipoDato = { "INTEGER", "TINYINT", "VARCHAR", "TIME", "YEAR", "BLOB" };
        
        for(String elemento : tipoDato){
            this.jComboBoxCampo.addItem(elemento);
        }
        
        this.jComboBoxUserDB.removeAllItems();
        String[] dbName = { "album", "cancion" };
        
        for(String elemento : dbName){
            this.jComboBoxUserDB.addItem(elemento);
        }
        
        this.jComboBoxAlbum.removeAllItems();
        ArrayList<String> titulosAlbum = conector.getTitulosAlbum();
        if(titulosAlbum != null) {
            titulosAlbum.forEach((elemento) -> this.jComboBoxAlbum.addItem(elemento));
        }
        
    }//GEN-LAST:event_jButtonConexionActionPerformed

    private void jButtonDesconexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDesconexionActionPerformed
        
        if(conector.cerrarConexion() == -1){
            this.jLabelMensaje.setText("Error al cerrar la conexión.");
            this.jButtonConexion.setEnabled(false);
            this.jButtonDesconexion.setEnabled(false);
            this.jButtonAnnadirCampo.setEnabled(false);
            this.jButtonMostrarAlbumes.setEnabled(false);
            this.jButtonAnnadirAlbum.setEnabled(false);
            this.jButtonAnnadirCancion.setEnabled(false);
        } else {
            this.jLabelMensaje.setText("Conexión cerrada correctamente.");
            this.jButtonConexion.setEnabled(true);
            this.jButtonDesconexion.setEnabled(false);
            this.jButtonAnnadirCampo.setEnabled(false);
            this.jButtonMostrarAlbumes.setEnabled(false);
            this.jButtonAnnadirAlbum.setEnabled(false);
            this.jButtonAnnadirCancion.setEnabled(false);
        }
        
    }//GEN-LAST:event_jButtonDesconexionActionPerformed

    private void jButtonAnnadirCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnadirCampoActionPerformed
            
        int resultadoModificacion = conector.annadirCampo(this.jTextFieldAnnadirCampo.getText(), this.jComboBoxCampo.getSelectedItem().toString());
        
        switch (resultadoModificacion) {
            case -1:
                this.jLabelMensaje.setText("La columna existe en la base de datos.");
                this.jButtonConexion.setEnabled(false);
                this.jButtonDesconexion.setEnabled(true);
                this.jButtonAnnadirCampo.setEnabled(false);
                this.jButtonMostrarAlbumes.setEnabled(true);
                break;
            case -2:
                this.jLabelMensaje.setText("Error al añadir publicación.");
                this.jButtonConexion.setEnabled(false);
                this.jButtonDesconexion.setEnabled(true);
                this.jButtonAnnadirCampo.setEnabled(false);
                this.jButtonMostrarAlbumes.setEnabled(true);
                break;
            default:
                this.jLabelMensaje.setText("Columna añadida satisfactoriamente.");
                this.jButtonConexion.setEnabled(false);
                this.jButtonDesconexion.setEnabled(true);
                this.jButtonAnnadirCampo.setEnabled(false);
                this.jButtonMostrarAlbumes.setEnabled(true);
                break;
        }
        
    }//GEN-LAST:event_jButtonAnnadirCampoActionPerformed

    private void jButtonMostrarAlbumesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarAlbumesActionPerformed
        
       this.jTextAreaSalida.setText(conector.consultaAlbum_Statement(this.jComboBoxUserDB.getSelectedItem().toString()));
       
    }//GEN-LAST:event_jButtonMostrarAlbumesActionPerformed

    private void jButtonAnnadirAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnadirAlbumActionPerformed
        
        if(conector.annadirAlbum(jTextFieldTituloAlbum.getText(), jTextFieldGrupo.getText(), jTextFieldDuracionAlbum.getText(), jTextFieldProductor.getText()) == -1){
            this.jLabelMensaje.setText("Error al añadir album.");
        } else {
            this.jLabelMensaje.setText("Album añadido satisfactoriamente.");
        }
        
    }//GEN-LAST:event_jButtonAnnadirAlbumActionPerformed

    private void jButtonAnnadirCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnadirCancionActionPerformed
        
        if(conector.annadirCancion(jTextFieldTituloCancion.getText(), jTextFieldDuracionCancion.getText(), jTextFieldEscritor.getText(), jComboBoxAlbum.getSelectedIndex()) == -1){
            this.jLabelMensaje.setText("Error al añadir canción.");
        } else {
            this.jLabelMensaje.setText("Canción añadida satisfactoriamente.");
        }
        
    }//GEN-LAST:event_jButtonAnnadirCancionActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnadirAlbum;
    private javax.swing.JButton jButtonAnnadirCampo;
    private javax.swing.JButton jButtonAnnadirCancion;
    private javax.swing.JButton jButtonConexion;
    private javax.swing.JButton jButtonDesconexion;
    private javax.swing.JButton jButtonMostrarAlbumes;
    private javax.swing.JComboBox<String> jComboBoxAlbum;
    private javax.swing.JComboBox<String> jComboBoxCampo;
    private javax.swing.JComboBox<String> jComboBoxUserDB;
    private javax.swing.JLabel jLabelAlbum;
    private javax.swing.JLabel jLabelDuracionCancion;
    private javax.swing.JLabel jLabelEscritor;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JLabel jLabelTituloAlbum;
    private javax.swing.JLabel jLabelTituloCancion;
    private javax.swing.JLabel jLabelTituloDuracionAlbum;
    private javax.swing.JLabel jLabelTituloGrupo;
    private javax.swing.JLabel jLabelTituloProductor;
    private javax.swing.JPanel jPanelAdmin;
    private javax.swing.JPanel jPanelUser;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextAreaSalida;
    private javax.swing.JTextField jTextFieldAnnadirCampo;
    private javax.swing.JTextField jTextFieldDuracionAlbum;
    private javax.swing.JTextField jTextFieldDuracionCancion;
    private javax.swing.JTextField jTextFieldEscritor;
    private javax.swing.JTextField jTextFieldGrupo;
    private javax.swing.JTextField jTextFieldProductor;
    private javax.swing.JTextField jTextFieldTituloAlbum;
    private javax.swing.JTextField jTextFieldTituloCancion;
    // End of variables declaration//GEN-END:variables
}
